### ISSUE TITLE
error with latest CELib

### ISSUE THREAD

**Issue by campbebj** [CebbysMods/slabref-mod#10]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'slabref'!
--
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: java.lang.NoSuchMethodError: com.cebbys.celib.registrators.BlockRegistry.registerBlock(Lnet/minecraft/class_2248;Ljava/lang/String;Ljava/lang/String;)V
at com.cebbys.slabref.content.blocks.DoubleSlabBlock.<init>(DoubleSlabBlock.java:16) ~[slabref-0.3.0.jar:?]
at com.cebbys.slabref.content.SlabrefSlabBlocks.<clinit>(SlabrefSlabBlocks.java:12) ~[slabref-0.3.0.jar:?]
at com.cebbys.slabref.SlabrefServer.initContent(SlabrefServer.java:11) ~[slabref-0.3.0.jar:?]
at com.cebbys.slabref.Slabref.onInitialize(Slabref.java:14) ~[slabref-0.3.0.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]

**Comment by CebbyS** [comment]
Thankyou, see the issue. Working on it!

**Comment by CebbyS** [comment]
Fixed the issue in latest update
