### ISSUE TITLE
1.17 version crash

### ISSUE THREAD

**Issue by K0-RR** [CebbysMods/slabref-mod#12]
```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'advanced_runtime_resource_pack'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'rrp:pregen' provided by 'refabslab'
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:167)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:259)
	at net.devtech.arrp.ARRP.onPreLaunch(ARRP.java:18)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: Class lv.cebbys.mcmods.refabslab.resources.ResourceEntrypoint cannot be cast to net.devtech.arrp.api.RRPPreGenEntrypoint!
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:63)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:160)
	... 14 more
Process exited with code 255.

```

**Comment by CebbyS** [comment]
Hi. Issue is that I forgot to remove entrypoint for rrp resource generator reference in farbic.mod,json. For now you can manually extract the zip file and edit the fabric.mod.json file

```
  "entrypoints": {
    "main": [
      "lv.cebbys.mcmods.refabslab.Refabslab"
    ],
    "client": [
      "lv.cebbys.mcmods.refabslab.Refabslab"
    ],
    "rrp:pregen": [
      "lv.cebbys.mcmods.refabslab.resources.ResourceEntrypoint"
    ]
  },
```

This has to be removed
```
    "rrp:pregen": [
      "lv.cebbys.mcmods.refabslab.resources.ResourceEntrypoint"
    ]
```

**Comment by CebbyS** [comment]
Thank you for pointing this out!
