### ISSUE TITLE
Crash on Fabric 1.17.1

### ISSUE THREAD

**Issue by Zano1999** [CebbysMods/slabref-mod#13]
It crash on startup.
Here the latest log file: https://pastebin.com/HtNtQ6Kg

**Comment by campbebj** [comment]
unsure if you're seeing the same error as me since your pastebin link is empty now, but here is my log
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'advanced_runtime_resource_pack'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:143)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'rrp:pregen' provided by 'refabslab'
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:167)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:259)
	at net.devtech.arrp.ARRP.onPreLaunch(ARRP.java:18)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: Class lv.cebbys.mcmods.refabslab.resources.ResourceEntrypoint cannot be cast to net.devtech.arrp.api.RRPPreGenEntrypoint!
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:63)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:160)
	... 14 more
```

**Comment by Zano1999** [comment]
The link had expired, I repost it below:

https://pastebin.com/cEDxRVnP

**Comment by CebbyS** [comment]
Hi!
The issue is that my mod contains rrp (RuntimeResource) entry in fabric.mod.json file. Which no longer exists in the latest version of refabslab. The line has to be removed from fabric.mod.json file, you can do this on your pc while I am working on an update. It is under client entry. Just remove it and repack the jar file
```json
"entrypoints": {
    "main": [
      "com.cebbys.slabref.Slabref"
    ],
    "client": [
      "com.cebbys.slabref.Slabref"
    ]
    "rrp": [
       "xxx"
    ]
  },
```

**Comment by Zano1999** [comment]
Now the mod starts but does nothing

**Comment by CebbyS** [comment]
@Zano1999 Could you please run the mod with console enabled and try to place a slab on top of slab. There should be some exceptions why it is not working. Could you please paste them here?

Thanks!

**Comment by Zano1999** [comment]
The output after opening the world and doing what you told me with the plates:

https://pastebin.com/ELtPYqSm

Anyway, yesterday you told me to edit the fabric.json file to make the mod work, maybe I made something wrong that broke the mod?

Here is the modified json: https://pastebin.com/ssmvmgBk

**Comment by Zano1999** [comment]
Anyway, yesterday you told me to edit the fabric.json file to make the mod work, maybe I made something wrong that broke the mod?

Here is the modified json: https://pastebin.com/ssmvmgBk

**Comment by CebbyS** [comment]
In the latest release, this issue has been fixed. Thanks!
